"""FLASH paired-end UMI extraction — move UMI from read 2 into read 1 header (umi_tools)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# FLASH read-2 structure per PMC7026646 / GSE118265 umi-extract.sh:
# 2 nt random + 6 nt UMI + 5 nt random/barcode flank = 13 nt (matches R1 3' adapter clip).
FLASH_BC_PATTERN2 = "NNXXXXXXNNNNN"


def umi_output_basename(srr: str) -> str:
    """Upload FASTQ basename after UMI extract (single-end to Flow)."""
    return f"{srr.upper()}_1.umi.fastq.gz"


def cleaned_umi_basename(srr: str) -> str:
    return f"{srr.upper()}_1.umi.cleaned.fastq.gz"


def find_read2_fastq(fastq_dir: Path, srr: str) -> Path | None:
    srr = srr.upper()
    for name in (f"{srr}_2.fastq.gz", f"{srr}_2.fastq", f"{srr}.fastq.gz"):
        candidate = fastq_dir / name
        if candidate.is_file():
            return candidate
    matches = sorted(fastq_dir.glob(f"**/{srr}_2.fastq*"))
    return matches[0] if matches else None


def resolve_r1_for_umi(fastq_dir: Path, srr: str, *, prefer_cleaned: bool = True) -> Path | None:
    """R1 path for umi_tools --stdin (prefer *.cleaned.fastq.gz when present)."""
    srr = srr.upper()
    if prefer_cleaned:
        cleaned = fastq_dir / f"{srr}_1.cleaned.fastq.gz"
        if cleaned.is_file():
            return cleaned
    for name in (f"{srr}_1.fastq.gz", f"{srr}_1.fastq"):
        candidate = fastq_dir / name
        if candidate.is_file():
            return candidate
    matches = sorted(fastq_dir.glob(f"**/{srr}_1.fastq*"))
    return matches[0] if matches else None


def collect_flash_umi_pairs(
    fastq_dir: Path,
    srr_ids: list[str],
    *,
    prefer_cleaned_r1: bool = True,
) -> list[tuple[str, Path, Path]]:
    """Return (srr, r1, r2) tuples when both mates exist."""
    pairs: list[tuple[str, Path, Path]] = []
    for srr in srr_ids:
        r1 = resolve_r1_for_umi(fastq_dir, srr, prefer_cleaned=prefer_cleaned_r1)
        r2 = find_read2_fastq(fastq_dir, srr)
        if r1 and r2:
            pairs.append((srr.upper(), r1, r2))
    return pairs


def write_umi_extract_script(
    output_dir: Path,
    pairs: list[tuple[str, Path, Path]],
    *,
    bc_pattern2: str = FLASH_BC_PATTERN2,
    parallel_jobs: int = 4,
) -> Path | None:
    """
    Write umi_extract.sh (umi_tools extract: UMI from R2 → R1 header).

    umi_tools extract is single-threaded; libraries run concurrently up to
  parallel_jobs (default 4). Override at runtime: PARALLEL_JOBS=2 bash umi_extract.sh

    Requires `umi_tools` on PATH (e.g. conda env umi-tools). Outputs *_1.umi.fastq.gz
    beside the input FASTQs; upload uses R1 only (no File 2).
    """
    if not pairs:
        return None

    script = output_dir / "umi_extract.sh"
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — FLASH UMI extract (see projects/flash/umi-extract.sh)",
        "# umi_tools moves UMI from read 2 into read 1 headers; Flow upload is SE (R1 only).",
        f'BC_PATTERN2="{bc_pattern2}"',
        f'PARALLEL_JOBS="${{PARALLEL_JOBS:-{parallel_jobs}}}"',
        'UMI_TOOLS="${UMI_TOOLS:-}"',
        'if [[ -z "$UMI_TOOLS" ]] && command -v umi_tools >/dev/null 2>&1; then UMI_TOOLS=umi_tools; fi',
        'if [[ -z "$UMI_TOOLS" ]] && [[ -x "${HOME}/miniconda3/envs/umi-tools/bin/umi_tools" ]]; then',
        '  UMI_TOOLS="${HOME}/miniconda3/envs/umi-tools/bin/umi_tools"',
        "fi",
        'if [[ -z "$UMI_TOOLS" ]]; then',
        '  echo "umi_tools not found — set UMI_TOOLS or conda activate umi-tools" >&2',
        "  exit 1",
        "fi",
        "",
        "extract_one() {",
        '  local srr="$1" r1="$2" r2="$3" out_r1="$4" out_r2="$5" log="$6"',
        '  echo "UMI extract ${srr}: $(basename "$r1") + $(basename "$r2")"',
        '  "$UMI_TOOLS" extract \\',
        '    --stdin "$r1" \\',
        '    --read2-in "$r2" \\',
        '    --stdout "$out_r1" \\',
        '    --read2-out="$out_r2" \\',
        '    --bc-pattern2="$BC_PATTERN2" \\',
        "    --extract-method=string \\",
        '    --log "$log"',
        "}",
        "",
        "pids=()",
    ]
    for srr, r1, r2 in pairs:
        out_r1 = r1.parent / umi_output_basename(srr)
        log = output_dir / "logs" / f"{srr}.umi_extract.log"
        out_r2 = r2.parent / f"{srr}_2.stripped.fastq.gz"
        lines.extend(
            [
                "extract_one \\",
                f'  "{srr}" \\',
                f'  "{r1.resolve()}" \\',
                f'  "{r2.resolve()}" \\',
                f'  "{out_r1.resolve()}" \\',
                f'  "{out_r2.resolve()}" \\',
                f'  "{log.resolve()}" &',
                "pids+=($!)",
                'while ((${#pids[@]} >= PARALLEL_JOBS)); do',
                "  wait \"${pids[0]}\"",
                "  pids=(${pids[@]:1})",
                "done",
                "",
            ]
        )
    lines.extend(
        [
            "for pid in \"${pids[@]}\"; do",
            '  wait "$pid"',
            "done",
            'echo "Done. Upload annotation should use *_1.umi.fastq.gz (read 1 only)."',
        ]
    )
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    (output_dir / "logs").mkdir(parents=True, exist_ok=True)
    return script


def planned_flash_umi_pairs(
    fastq_dir: Path,
    srr_ids: list[str],
    *,
    prefer_cleaned_r1: bool = True,
) -> list[tuple[str, Path, Path]]:
    """Expected R1/R2 paths for umi_extract.sh when mates are not on disk yet."""
    pairs: list[tuple[str, Path, Path]] = []
    for srr in srr_ids:
        srr = srr.upper()
        r1 = resolve_r1_for_umi(fastq_dir, srr, prefer_cleaned=prefer_cleaned_r1)
        if r1 is None:
            r1 = (
                fastq_dir / f"{srr}_1.cleaned.fastq.gz"
                if prefer_cleaned_r1
                else fastq_dir / f"{srr}_1.fastq.gz"
            )
        r2 = find_read2_fastq(fastq_dir, srr) or (fastq_dir / f"{srr}_2.fastq.gz")
        pairs.append((srr, r1, r2))
    return pairs


def srr_from_annotation_file(filename: str) -> str:
    match = re.search(r"(SRR\d+)", str(filename))
    return match.group(1).upper() if match else ""


def apply_umi_extracted_filenames(annotation: Any) -> Any:
    """Point File at *_1.umi.fastq.gz and clear File 2 (SE upload after UMI extract)."""
    if "File" not in getattr(annotation, "columns", []):
        return annotation
    updated = annotation.copy()
    updated["File"] = updated["File"].apply(
        lambda name: umi_output_basename(srr_from_annotation_file(str(name)))
        if srr_from_annotation_file(str(name))
        else name
    )
    if "File 2" in updated.columns:
        updated["File 2"] = ""
    return updated


def apply_cleaned_umi_filenames(annotation: Any) -> Any:
    """Point File at *_1.umi.cleaned.fastq.gz after removespace on UMI output."""
    if "File" not in getattr(annotation, "columns", []):
        return annotation
    updated = annotation.copy()

    def _to_cleaned(name: str) -> str:
        srr = srr_from_annotation_file(str(name))
        if not srr:
            return name
        if str(name).endswith(".umi.fastq.gz"):
            return cleaned_umi_basename(srr)
        return name

    updated["File"] = updated["File"].apply(_to_cleaned)
    return updated
