"""Generate upload and CLIP analysis shell scripts for advbfx Flow API tools."""

from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd


def resolve_advbfx_script(name: str, explicit: Path | None = None) -> Path | None:
    if explicit and explicit.is_file():
        return explicit.resolve()
    for candidate in (
        Path("/home/mikej10/advbfx/flowAPIscripts") / name,
        Path.cwd() / "flowAPIscripts" / name,
        Path.cwd().parent / "flowAPIscripts" / name,
    ):
        if candidate.is_file():
            return candidate.resolve()
    return None


def _srr_from_file(filename: str) -> str:
    match = re.search(r"(SRR\d+)", str(filename))
    return match.group(1) if match else ""


def sample_name_filter_from_annotation(annotation: pd.DataFrame) -> str:
    """Build a sample_name regex matching uploaded SRR ids."""
    srrs = [_srr_from_file(row.get("File", "")) for _, row in annotation.iterrows()]
    srrs = [s for s in srrs if s]
    if not srrs:
        return ".*"
    return "|".join(re.escape(s) for s in srrs)


def experimental_method_from_annotation(annotation: pd.DataFrame) -> str:
    if "Experimental Method" not in annotation.columns:
        return "iCLIP"
    methods = annotation["Experimental Method"].dropna().astype(str).str.strip()
    methods = [m for m in methods if m]
    return methods[0] if methods else "iCLIP"


def write_upload_script(
    output_dir: Path,
    *,
    upload_script: Path,
    annotation_path: Path,
    project_id: str,
    base_dir: Path,
    row_count: int,
    dry_run: bool = True,
) -> Path:
    script = output_dir / "upload.sh"
    rows = f"1-{row_count}" if row_count > 1 else "1"
    flag = " --dry-run" if dry_run else ""
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — upload samples via uploadsample_flowbio_v6.py",
        "# Requires FLOWBIO_USERNAME / FLOWBIO_PASSWORD (or --username/--password)",
        f'ENV_FILE="{output_dir.resolve()}/.flow_credentials.env"',
        "if [[ -f \"$ENV_FILE\" ]]; then source \"$ENV_FILE\"; fi",
        f'ANNOTATION="{annotation_path.resolve()}"',
        f'BASE_DIR="{base_dir.resolve()}"',
        f'PROJECT_ID="{project_id}"',
        f'UPLOAD="{upload_script}"',
        "",
        f'python3 "$UPLOAD" \\',
        f'  --input "$ANNOTATION" \\',
        f'  --rows {rows} \\',
        f'  --project-id "$PROJECT_ID" \\',
        f'  --base-dir "$BASE_DIR"{flag}',
    ]
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)

    live_lines = lines[:-1] + ['  --base-dir "$BASE_DIR"']
    live = output_dir / "upload_live.sh"
    live.write_text("\n".join(live_lines) + "\n")
    live.chmod(0o755)
    return script


def write_analysis_script(
    output_dir: Path,
    *,
    analysis_script: Path,
    project_id: str,
    pipeline_params: dict[str, str],
    sample_name_filter: str,
    experimental_method: str,
    num_chunks: int = 1,
) -> Path:
    script = output_dir / "run_analysis.sh"
    params_path = output_dir / "pipeline_params.json"
    confirmed_params_path = output_dir / "analysis_params.confirmed.json"
    params_path.write_text(json.dumps(pipeline_params, indent=2))

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — submit CLIP-Seq analysis via flowrunanalysis_flowbio.py",
        "# Uses FLOWBIO_USERNAME / FLOWBIO_PASSWORD; --yes skips submit confirmation",
        "# Manual gate: see CONFIRM_ANALYSIS_PARAMS.md; analysis_params.confirmed.json must match pipeline_params.json",
        f'ENV_FILE="{output_dir.resolve()}/.flow_credentials.env"',
        "if [[ -f \"$ENV_FILE\" ]]; then source \"$ENV_FILE\"; fi",
        f'ANALYSIS="{analysis_script.resolve()}"',
        f'PARAMS="{params_path.resolve()}"',
        f'CONFIRMED_PARAMS="{confirmed_params_path.resolve()}"',
        f'PROJECT_ID="{project_id}"',
        "",
        "if [[ ! -f \"$CONFIRMED_PARAMS\" ]]; then",
        "  echo \"Manual check required before analysis.\" >&2",
        "  echo \"Review params in: $PARAMS\" >&2",
        "  echo \"When verified, run:\" >&2",
        "  echo \"  cp \\\"$PARAMS\\\" \\\"$CONFIRMED_PARAMS\\\"\" >&2",
        "  exit 3",
        "fi",
        "",
        "if ! cmp -s \"$PARAMS\" \"$CONFIRMED_PARAMS\"; then",
        "  echo \"analysis_params.confirmed.json is out of date.\" >&2",
        "  echo \"Re-verify $PARAMS and refresh confirmation:\" >&2",
        "  echo \"  cp \\\"$PARAMS\\\" \\\"$CONFIRMED_PARAMS\\\"\" >&2",
        "  exit 3",
        "fi",
        "",
        'python3 "$ANALYSIS" \\',
        f'  --pid "$PROJECT_ID" \\',
        f'  --filter sample_name "{sample_name_filter}" \\',
        f'  --filter experimental_method "{experimental_method}" \\',
        f'  --params-json "$PARAMS" \\',
        f"  -n {num_chunks} \\",
        '  --yes',
    ]
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script
