"""Generate upload and CLIP analysis shell scripts for advbfx Flow API tools."""

from __future__ import annotations

from pathlib import Path as _Path


#: The skill root, so a generated script can import lib/ wherever it is run from.
SKILL_DIR = _Path(__file__).resolve().parent.parent

import json
import shlex
import re
from pathlib import Path

import pandas as pd




def _srr_from_file(filename: str) -> str:
    match = re.search(r"(SRR\d+)", str(filename))
    return match.group(1) if match else ""


def sample_name_filter_from_annotation(annotation: pd.DataFrame) -> str:
    """Build a sample_name regex matching uploaded SRR ids."""
    srrs = [_srr_from_file(row.get("File", "")) for _, row in annotation.iterrows()]
    srrs = [s for s in srrs if s]
    if not srrs:
        return ".*"
    return "|".join(re.escape(s) for s in srrs)


def write_analysis_script(
    output_dir: Path,
    *,
    analysis_script: Path,
    project_id: str,
    pipeline_params: dict[str, str],
    sample_name_filter: str,
    experimental_method: str,
    num_chunks: int = 1,
) -> Path:
    script = output_dir / "run_analysis.sh"
    params_path = output_dir / "pipeline_params.json"
    params_path.write_text(json.dumps(pipeline_params, indent=2))

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — submit CLIP-Seq analysis via flowrunanalysis_flowbio.py",
        "# Auth: FLOWBIO_USERNAME / FLOWBIO_PASSWORD, or FLOW_API_TOKEN / FLOW_TOKEN.",
        f'ANALYSIS="{analysis_script.resolve()}"',
        f'PARAMS="{params_path.resolve()}"',
        f'PROJECT_ID="{project_id}"',
        "",
        'python3 "$ANALYSIS" \\',
        f'  --pid "$PROJECT_ID" \\',
        *([f"  --filter sample_name {shlex.quote(sample_name_filter)} \\"]
          if sample_name_filter else []),
        f'  --filter experimental_method "{experimental_method}" \\',
        f'  --params-json "$PARAMS" \\',
        f"  -n {num_chunks} \\",
        '  --yes',
    ]
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script
