"""Detect problematic FASTQ headers and generate removespace.py batch script."""

from __future__ import annotations

import re
from pathlib import Path


def headers_need_cleaning(header_lines: list[str]) -> bool:
    """True when sampled @ lines contain slashes, spaces, or underscore barcodes."""
    for line in header_lines:
        if not line.startswith("@"):
            continue
        body = line[1:]
        if "/" in body or " " in body:
            return True
        if "_" in body:
            return True
    return False


def cleaned_fastq_name(fastq_path: Path) -> str:
    """Output filename that removespace.py produces by default."""
    name = fastq_path.name
    if name.endswith(".fastq.gz"):
        return name.replace(".fastq.gz", ".cleaned.fastq.gz")
    if name.endswith(".fastq"):
        return name.replace(".fastq", ".cleaned.fastq.gz")
    return f"{name}.cleaned.fastq.gz"


def resolve_removespace_script(explicit: Path | None = None) -> Path | None:
    if explicit:
        return explicit if explicit.is_file() else None
    for candidate in (
        Path("/home/mikej10/advbfx/flowAPIscripts/preprocessing/removespace.py"),
        Path.cwd() / "flowAPIscripts/preprocessing/removespace.py",
        Path.cwd().parent / "flowAPIscripts/preprocessing/removespace.py",
    ):
        if candidate.is_file():
            return candidate.resolve()
    return None


def write_clean_fastq_script(
    output_dir: Path,
    fastq_paths: list[Path],
    *,
    removespace_script: Path,
) -> Path | None:
    """Write clean_fastq.sh to run removespace.py on each input FASTQ."""
    if not fastq_paths:
        return None

    script = output_dir / "clean_fastq.sh"
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — normalizes FASTQ headers (spaces/slashes -> underscore)",
        f"REMOVESPACE={removespace_script}",
        'if ! command -v pigz >/dev/null 2>&1; then',
        '  echo "pigz required for removespace.py" >&2',
        "  exit 1",
        "fi",
        "",
    ]
    for fq in fastq_paths:
        fq_abs = fq.resolve()
        out_name = cleaned_fastq_name(fq_abs)
        out_path = fq_abs.parent / out_name
        lines.append(f'echo "Cleaning {fq_abs.name} -> {out_name}"')
        lines.append(f'python3 "$REMOVESPACE" "{fq_abs}" "{out_path}"')
        lines.append("")

    lines.append('echo "Done. Upload/analysis should use *.cleaned.fastq.gz files."')
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script


def write_upload_manifest(output_dir: Path, fastq_paths: list[Path]) -> Path | None:
    """Map raw FASTQ names to cleaned names for upload."""
    if not fastq_paths:
        return None
    manifest = output_dir / "fastq_upload_manifest.tsv"
    rows = ["raw_fastq\tcleaned_fastq\tuse_for_upload"]
    for fq in fastq_paths:
        cleaned = cleaned_fastq_name(fq)
        rows.append(f"{fq.name}\t{cleaned}\t{cleaned}")
    manifest.write_text("\n".join(rows) + "\n")
    return manifest
