"""uvCLAP paired-end UMI extraction — move 5' and 3' barcodes into read headers (umi_tools)."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# R1: NNNTTTTTNN (10 nt) — all positions to UMI; full block stripped from sequence.
# R2: 5 nt 3'-barcode (semi-random replicate tag) at read start.
UVCLAP_BC_PATTERN = "NNNNNNNNNN"
UVCLAP_BC_PATTERN2 = "NNNNN"


def umi_output_basename(srr: str, mate: int = 1) -> str:
    """FASTQ basename after UMI extract (paired-end upload to Flow)."""
    return f"{srr.upper()}_{mate}.umi.fastq.gz"


def find_mate_fastq(fastq_dir: Path, srr: str, mate: int) -> Path | None:
    srr = srr.upper()
    for name in (f"{srr}_{mate}.fastq.gz", f"{srr}_{mate}.fastq"):
        candidate = fastq_dir / name
        if candidate.is_file():
            return candidate
    matches = sorted(fastq_dir.glob(f"**/{srr}_{mate}.fastq*"))
    return matches[0] if matches else None


def collect_uvclap_umi_pairs(
    fastq_dir: Path,
    srr_ids: list[str],
) -> list[tuple[str, Path, Path]]:
    """Return (srr, r1, r2) tuples when both mates exist."""
    pairs: list[tuple[str, Path, Path]] = []
    for srr in srr_ids:
        r1 = find_mate_fastq(fastq_dir, srr, 1)
        r2 = find_mate_fastq(fastq_dir, srr, 2)
        if r1 and r2:
            pairs.append((srr.upper(), r1, r2))
    return pairs


def planned_uvclap_umi_pairs(fastq_dir: Path, srr_ids: list[str]) -> list[tuple[str, Path, Path]]:
    """Expected R1/R2 paths for umi_extract.sh when mates are not on disk yet."""
    pairs: list[tuple[str, Path, Path]] = []
    for srr in srr_ids:
        srr = srr.upper()
        r1 = find_mate_fastq(fastq_dir, srr, 1) or (fastq_dir / f"{srr}_1.fastq.gz")
        r2 = find_mate_fastq(fastq_dir, srr, 2) or (fastq_dir / f"{srr}_2.fastq.gz")
        pairs.append((srr, r1, r2))
    return pairs


def write_umi_extract_script(
    output_dir: Path,
    pairs: list[tuple[str, Path, Path]],
    *,
    bc_pattern: str = UVCLAP_BC_PATTERN,
    bc_pattern2: str = UVCLAP_BC_PATTERN2,
    parallel_jobs: int = 4,
) -> Path | None:
    """
    Write umi_extract.sh (umi_tools extract: 5' UMI on R1 + 3' barcode on R2).

    Keeps both mates for paired-end Flow upload. Override concurrency:
      PARALLEL_JOBS=2 bash umi_extract.sh
    """
    if not pairs:
        return None

    script = output_dir / "umi_extract.sh"
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — uvCLAP UMI extract (paired-end)",
        "# Strips R1 NNNTTTTTNN (10 nt) and R2 5 nt 3'-barcode; UMIs in read headers.",
        f'BC_PATTERN="{bc_pattern}"',
        f'BC_PATTERN2="{bc_pattern2}"',
        f'PARALLEL_JOBS="${{PARALLEL_JOBS:-{parallel_jobs}}}"',
        'UMI_TOOLS="${UMI_TOOLS:-}"',
        'if [[ -z "$UMI_TOOLS" ]] && command -v umi_tools >/dev/null 2>&1; then UMI_TOOLS=umi_tools; fi',
        'if [[ -z "$UMI_TOOLS" ]] && [[ -x "${HOME}/miniconda3/envs/umi-tools/bin/umi_tools" ]]; then',
        '  UMI_TOOLS="${HOME}/miniconda3/envs/umi-tools/bin/umi_tools"',
        "fi",
        'if [[ -z "$UMI_TOOLS" ]]; then',
        '  echo "umi_tools not found — set UMI_TOOLS or conda activate umi-tools" >&2',
        "  exit 1",
        "fi",
        "",
        "extract_one() {",
        '  local srr="$1" r1="$2" r2="$3" out_r1="$4" out_r2="$5" log="$6"',
        '  echo "UMI extract ${srr}: $(basename "$r1") + $(basename "$r2")"',
        '  "$UMI_TOOLS" extract \\',
        '    --stdin "$r1" \\',
        '    --read2-in "$r2" \\',
        '    --stdout "$out_r1" \\',
        '    --read2-out="$out_r2" \\',
        '    --bc-pattern="$BC_PATTERN" \\',
        '    --bc-pattern2="$BC_PATTERN2" \\',
        "    --extract-method=string \\",
        '    --log "$log"',
        "}",
        "",
        "pids=()",
    ]
    for srr, r1, r2 in pairs:
        out_r1 = r1.parent / umi_output_basename(srr, 1)
        out_r2 = r2.parent / umi_output_basename(srr, 2)
        log = output_dir / "logs" / f"{srr}.umi_extract.log"
        lines.extend(
            [
                "extract_one \\",
                f'  "{srr}" \\',
                f'  "{r1.resolve()}" \\',
                f'  "{r2.resolve()}" \\',
                f'  "{out_r1.resolve()}" \\',
                f'  "{out_r2.resolve()}" \\',
                f'  "{log.resolve()}" &',
                "pids+=($!)",
                'while ((${#pids[@]} >= PARALLEL_JOBS)); do',
                "  wait \"${pids[0]}\"",
                "  pids=(${pids[@]:1})",
                "done",
                "",
            ]
        )
    lines.extend(
        [
            "for pid in \"${pids[@]}\"; do",
            '  wait "$pid"',
            "done",
            'echo "Done. Upload *_1.umi.fastq.gz + *_2.umi.fastq.gz (paired-end)."',
        ]
    )
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    (output_dir / "logs").mkdir(parents=True, exist_ok=True)
    return script


def write_merge_pe_script(
    output_dir: Path,
    merges: list[tuple[str, list[str]]],
    *,
    fastq_dir: Path,
) -> Path | None:
    """
    Write merge_pe.sh — cat per-SRR UMI FASTQs into one PE pair per GSM.

    merges: [(gsm_id, [srr1, srr2, ...]), ...]
    """
    if not merges:
        return None
    script = output_dir / "merge_pe.sh"
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — merge technical SRR runs per GSM (paired-end)",
        f'FASTQ_DIR="{fastq_dir.resolve()}"',
        "cd \"$FASTQ_DIR\"",
        "",
    ]
    for gsm, srrs in merges:
        r1_out = f"{gsm}_1.umi.fastq.gz"
        r2_out = f"{gsm}_2.umi.fastq.gz"
        r1_parts = " ".join(f'"{srr}_1.umi.fastq.gz"' for srr in srrs)
        r2_parts = " ".join(f'"{srr}_2.umi.fastq.gz"' for srr in srrs)
        lines.extend(
            [
                f'echo "Merging {gsm} ({len(srrs)} SRRs)"',
                f"cat {r1_parts} > {r1_out}",
                f"cat {r2_parts} > {r2_out}",
                "",
            ]
        )
    lines.append('echo "Merged PE FASTQs in $(pwd)"')
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script


def gsm_merge_plan_from_srr_map(srr_map) -> list[tuple[str, list[str]]]:
    """Group SRR accessions by GSM from a flow-compile srr_map DataFrame."""
    merges: list[tuple[str, list[str]]] = []
    for gsm, rows in srr_map.groupby("gsm", sort=False):
        srrs = [str(s).upper() for s in rows["srr"].tolist()]
        merges.append((str(gsm), srrs))
    return merges


def srr_from_annotation_file(filename: str) -> str:
    match = re.search(r"(SRR\d+)", str(filename))
    return match.group(1).upper() if match else ""


def apply_uvclap_umi_filenames(annotation: Any) -> Any:
    """Point File / File 2 at *_1.umi.fastq.gz and *_2.umi.fastq.gz."""
    if "File" not in getattr(annotation, "columns", []):
        return annotation
    updated = annotation.copy()
    for idx, row in updated.iterrows():
        srr = srr_from_annotation_file(str(row.get("File", "")))
        if not srr:
            continue
        updated.at[idx, "File"] = umi_output_basename(srr, 1)
        if "File 2" in updated.columns:
            updated.at[idx, "File 2"] = umi_output_basename(srr, 2)
    return updated


def apply_merged_gsm_filenames(annotation: Any, gsm: str) -> Any:
    """After merge_pe.sh, point File / File 2 at GSM-level merged PE pair."""
    if "File" not in getattr(annotation, "columns", []):
        return annotation
    updated = annotation.copy()
    updated["File"] = f"{gsm}_1.umi.fastq.gz"
    if "File 2" in updated.columns:
        updated["File 2"] = f"{gsm}_2.umi.fastq.gz"
    return updated
