#!/usr/bin/env python3
"""Flow Compile — orchestrates CLIP literature → Flow annotation pipeline stages."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SKILL_DIR = Path(__file__).resolve().parent
if str(SKILL_DIR) not in sys.path:
    sys.path.insert(0, str(SKILL_DIR))

from lib.barcode_evidence import load_confirmed_proposals
from lib.barcode_extract import extract_barcodes_for_gsms, write_proposal_bundle
from lib.barcode_resolver import BarcodeResolution, resolve_barcodes
from lib.header_clean import (
    cleaned_fastq_name,
    headers_need_cleaning,
    resolve_removespace_script,
    write_clean_fastq_script,
    write_upload_manifest,
)
from lib.annotation_xlsx import write_annotation_xlsx
from lib.credentials import ensure_flow_credentials
from lib.flow_stages import (
    experimental_method_from_annotation,
    resolve_advbfx_script,
    sample_name_filter_from_annotation,
    write_analysis_script,
    write_upload_script,
)
from lib.process_runner import DEFAULT_POLL_INTERVAL_SEC, run_shell_step
from lib.workflow_runner import run_automated_workflow, write_run_workflow_script
from lib.fastq_headers import (
    build_headers_txt,
    inspection_to_dict,
    resolve_srr_fastq_paths,
    sample_headers_from_fastq_dir,
)
from lib.flash_umi_extract import (
    apply_umi_extracted_filenames,
    collect_flash_umi_pairs,
    planned_flash_umi_pairs,
    srr_from_annotation_file,
    umi_output_basename,
    write_umi_extract_script,
)
from lib.uvclap_umi_extract import (
    apply_uvclap_umi_filenames,
    collect_uvclap_umi_pairs,
    gsm_merge_plan_from_srr_map,
    planned_uvclap_umi_pairs,
    write_merge_pe_script,
    write_umi_extract_script as write_uvclap_umi_extract_script,
)
from lib.flow_annotate import build_annotation_table, load_srr_map
from lib.geo_matrix import parse_geo_matrix
from lib.pipeline_params import (
    derive_clip_pipeline_params,
    derive_flash_post_umi_params,
    derive_uvclap_post_umi_params,
    summarize_params_for_report,
    write_analysis_params_hook,
)
from lib.pubmed_stage import CLIP_ALERT_QUERY, run_pubmed_stage

DEMO_MATRIX = SKILL_DIR / "demo_geo_matrix.txt"
DEMO_SRR_MAP = SKILL_DIR / "demo_srr_map.tsv"
DEMO_PUBMED_CACHE = SKILL_DIR / "demo_pubmed_clip.json"
HNRNPH_MATRIX = SKILL_DIR / "demo_hnrnph_geo_matrix.txt"
HNRNPH_SRR_MAP = SKILL_DIR / "demo_hnrnph_srr_map.tsv"
HNRNPH_GEO_CACHE = SKILL_DIR / "demo" / "geo_GSM9118554.txt"
HNRNPH_PAPER = SKILL_DIR / "demo" / "paper_PMC6307142_iclip_excerpt.txt"
GSE105082_MATRIX = SKILL_DIR / "demo_gse105082_geo_matrix.txt"
GSE105082_SRR_MAP = SKILL_DIR / "demo_gse105082_srr_map.tsv"
GSE105082_GEO_CACHE = SKILL_DIR / "demo"
GSE105082_PAPER = SKILL_DIR / "demo" / "paper_PMC6307142_iclip_excerpt.txt"
GSE105082_FLOW_PROJECT_ID = "997999200849251656"
XL1_DHX9_MATRIX = SKILL_DIR / "demo_xl1_dhx9_geo_matrix.txt"
XL1_DHX9_SRR_MAP = SKILL_DIR / "demo_xl1_dhx9_srr_map.tsv"
XL1_DHX9_PAPER = SKILL_DIR / "demo" / "paper_PMC7026646_flash_excerpt.txt"
XL1_DHX9_FLOW_PROJECT_ID = "834759538599245747"
XL9_DHX9_MATRIX = SKILL_DIR / "demo_xl9_dhx9_geo_matrix.txt"
XL9_DHX9_SRR_MAP = SKILL_DIR / "demo_xl9_dhx9_srr_map.tsv"
XL9_DHX9_PAPER = SKILL_DIR / "demo" / "paper_PMC7026646_flash_excerpt.txt"
XL9_DHX9_FLOW_PROJECT_ID = "834759538599245747"
XL8_DHX9_MATRIX = SKILL_DIR / "demo_xl8_dhx9_geo_matrix.txt"
XL8_DHX9_SRR_MAP = SKILL_DIR / "demo_xl8_dhx9_srr_map.tsv"
XL8_DHX9_PAPER = SKILL_DIR / "demo" / "paper_PMC7026646_flash_excerpt.txt"
XL8_DHX9_FLOW_PROJECT_ID = "834759538599245747"
XL2_HNRNPC_MATRIX = SKILL_DIR / "demo_xl2_hnrnpc_geo_matrix.txt"
XL2_HNRNPC_SRR_MAP = SKILL_DIR / "demo_xl2_hnrnpc_srr_map.tsv"
XL2_HNRNPC_PAPER = SKILL_DIR / "demo" / "paper_PMC7026646_flash_excerpt.txt"
XL2_HNRNPC_FLOW_PROJECT_ID = "834759538599245747"
EXIT_PAUSED = 3


@dataclass
class WorkflowResult:
    gse: str
    pmid: str
    gsm_count: int
    file_count: int
    barcodes_resolved: int
    barcodes_total: int
    stages: dict[str, str]
    barcode_audit: list[dict[str, Any]]
    chain: list[str]
    flow_project_id: str = ""
    pipeline_params: dict[str, str] | None = None
    header_inspection: dict[str, Any] | None = None


def write_prefetch_script(
    output_dir: Path, fastqs: list[str], max_runs: int | None = None
) -> Path:
    script = output_dir / "prefetch.sh"
    seen_srr: set[str] = set()
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by flow-compile — review before running on HPC",
        "# After prefetch: fasterq-dump or `prefetch --max-size u` then fasterq-dump",
        "# Place .fastq.gz files in a single directory and pass --fastq-dir to flow-compile",
        "FASTQ_DIR=\"${FASTQ_DIR:-./fastq_files}\"",
        "mkdir -p \"$FASTQ_DIR\"",
        "cd \"$FASTQ_DIR\"",
    ]
    for fq in fastqs:
        match = re.search(r"(SRR\d+)", fq)
        if not match:
            continue
        srr = match.group(1)
        if srr in seen_srr:
            continue
        seen_srr.add(srr)
        lines.append(f"prefetch {srr}")
        lines.append(f"fasterq-dump {srr} --split-files --skip-technical --threads 4")
        lines.append(f"pigz -f {srr}_1.fastq {srr}_2.fastq 2>/dev/null || pigz -f {srr}.fastq")
        if max_runs is not None and max_runs > 0 and len(seen_srr) >= max_runs:
            break
    lines.append('echo "FASTQs in $(pwd)"')
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    return script


def generate_report(result: WorkflowResult, flagged: list[dict[str, Any]]) -> str:
    lines = [
        "# Flow Compile Report",
        "",
        f"**GSE:** {result.gse}  ",
        f"**PMID:** {result.pmid}  ",
        f"**Chain:** {' → '.join(result.chain)}  ",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Pipeline stages",
        "",
        "| Stage | Skill / module | Status |",
        "|-------|----------------|--------|",
    ]
    stage_skills = {
        "pubmed_alert": "pubmed-summariser",
        "geo_audit": "geo_matrix",
        "barcode_extract": "barcode_evidence (agent-assisted)",
        "barcode_resolver": "barcode_resolver / confirmed proposals",
        "flow_annotate": "flow_annotate",
        "fastq_headers": "fastq_headers",
        "header_clean": "removespace.py (clean_fastq.sh)",
        "annotation_xlsx": "annotation.xlsx",
        "flow_upload": "upload.sh",
        "flow_analysis": "run_analysis.sh",
        "pipeline_params": "pipeline_params",
        "prefetch": "prefetch.sh",
        "flow_upload": "uploadsample_flowbio_v6.py",
    }
    for stage, status in result.stages.items():
        lines.append(f"| {stage} | {stage_skills.get(stage, 'flow-compile')} | {status} |")

    lines.extend(["", "## Flagged CLIP papers", ""])
    if flagged:
        for paper in flagged:
            gse = paper.get("gse") or []
            gse_s = gse[0] if isinstance(gse, list) and gse else paper.get("gse", "")
            lines.append(f"- **PMID {paper.get('pmid')}** — {paper.get('title')} (`{gse_s}`)")
    else:
        lines.append("- _(none)_")

    lines.extend(
        [
            "",
            "## Barcode audit",
            "",
            "| GSM | Protocol | 5' Barcode | Confidence | Sources |",
            "|-----|----------|------------|------------|---------|",
        ]
    )
    for item in result.barcode_audit:
        sources = "; ".join(item.get("sources", []))
        lines.append(
            f"| {item['gsm']} | {item.get('protocol', '')} | `{item['five_prime']}` | "
            f"{item['confidence']} | {sources} |"
        )

    if result.pipeline_params:
        from lib.fastq_headers import HeaderInspection

        insp_obj = None
        if result.header_inspection:
            insp_obj = HeaderInspection(**result.header_inspection)
        lines.extend(["", summarize_params_for_report(result.pipeline_params, insp_obj).rstrip()])

    if result.flow_project_id:
        lines.extend(
            [
                "",
                "## Flow project",
                "",
                f"- **Project ID:** `{result.flow_project_id}`",
                f"- **URL:** https://app.flow.bio/projects/{result.flow_project_id}/",
            ]
        )

    lines.extend(
        [
            "",
            "*ClawBio is a research tool. Not a medical device.*",
        ]
    )
    return "\n".join(lines) + "\n"


def _resolve_barcodes_agent_assisted(
    matrix_data: dict[str, Any],
    *,
    paper_texts: list[tuple[str, Path]],
    geo_cache_dir: Path | None,
    fetch_geo: bool,
    accept_proposals: Path | None,
    output_dir: Path,
    require_confirmation: bool,
) -> tuple[dict[str, BarcodeResolution], dict[str, str], bool]:
    """
    Returns (barcode_by_gsm, stage_status, paused_for_confirmation).
    """
    gsms = list(matrix_data["samples"].keys())
    stages: dict[str, str] = {}

    if accept_proposals and accept_proposals.exists():
        confirmed = load_confirmed_proposals(accept_proposals)
        if not confirmed:
            stages["barcode_extract"] = "accept-proposals file has no confirmed rows"
            return {}, stages, True
        by_gsm = {
            gsm: BarcodeResolution(
                gsm=gsm,
                five_prime=p.five_prime,
                three_prime=p.umi_barcode,
                protocol=p.protocol,
                confidence="high",
                sources=["human_confirmed"],
                notes=p.agent_notes,
            )
            for gsm, p in confirmed.items()
        }
        stages["barcode_resolver"] = f"{len(by_gsm)} human-confirmed barcode(s)"
        return by_gsm, stages, False

    if not paper_texts and not geo_cache_dir and not fetch_geo:
        resolutions = resolve_barcodes(matrix_data["samples"])
        by_gsm = {r.gsm: r for r in resolutions}
        resolved = sum(1 for r in resolutions if r.five_prime)
        stages["barcode_resolver"] = f"{resolved}/{len(resolutions)} resolved (heuristic)"
        return by_gsm, stages, False

    proposals = extract_barcodes_for_gsms(
        gsms,
        paper_texts=paper_texts,
        geo_cache_dir=geo_cache_dir,
        fetch_geo=fetch_geo,
        sample_titles={gsm: matrix_data["samples"][gsm].get("title", "") for gsm in gsms},
    )
    proposal_path = write_proposal_bundle(output_dir, proposals)
    stages["barcode_extract"] = f"{len(proposals)} proposal(s) → {proposal_path.name}"

    if require_confirmation:
        stages["barcode_resolver"] = "paused — awaiting human confirmation"
        return {}, stages, True

    by_gsm = {}
    for p in proposals:
        by_gsm[p.gsm] = BarcodeResolution(
            gsm=p.gsm,
            five_prime=p.five_prime,
            three_prime=p.umi_barcode,
            protocol=p.protocol,
            confidence=p.confidence,
            sources=[e.kind for e in p.evidence],
            notes=p.agent_notes,
        )
    stages["barcode_resolver"] = f"{len(by_gsm)} auto-accepted (no --require-confirmation)"
    return by_gsm, stages, False


def _apply_cleaned_filenames(annotation) -> tuple[Any, bool]:
    """Point File column at *.cleaned.fastq.gz when header cleaning is planned."""
    if "File" not in annotation.columns:
        return annotation, False
    updated = annotation.copy()
    updated["File"] = updated["File"].apply(
        lambda name: cleaned_fastq_name(Path(str(name))) if str(name).strip() else name
    )
    return updated, True


def _annotation_is_flash(annotation, matrix_data: dict[str, Any] | None = None) -> bool:
    if "Experimental Method" in annotation.columns:
        methods = annotation["Experimental Method"].dropna().astype(str).str.strip().str.upper()
        if (methods == "FLASH").any():
            return True
    if matrix_data:
        blob = " ".join(
            str(s.get("extract_protocol_ch1", "")) for s in matrix_data.get("samples", {}).values()
        )
        if "flash" in blob.lower():
            return True
    return False


def _annotation_is_uvclap(annotation, matrix_data: dict[str, Any] | None = None) -> bool:
    if "Experimental Method" in annotation.columns:
        methods = annotation["Experimental Method"].dropna().astype(str).str.strip().str.upper()
        if (methods == "UVCLAP").any():
            return True
    if matrix_data:
        blob = " ".join(
            str(s.get("extract_protocol_ch1", "")) for s in matrix_data.get("samples", {}).values()
        )
        if "uvclap" in blob.lower():
            return True
    return False


def _setup_uvclap_umi_stage(
    output_dir: Path,
    annotation,
    srr_map_df,
    fastq_dir: Path | None,
) -> tuple[Any, str, str]:
    """Write umi_extract.sh (+ merge_pe.sh) and retarget annotation to PE UMI FASTQs."""
    srr_ids = list(
        dict.fromkeys(
            srr_from_annotation_file(str(row.get("File", "")))
            for _, row in annotation.iterrows()
            if srr_from_annotation_file(str(row.get("File", "")))
        )
    )
    if not srr_ids:
        return annotation, "skipped — no SRR in annotation", ""

    merge_stage = ""
    merges = gsm_merge_plan_from_srr_map(srr_map_df)
    if fastq_dir and merges:
        merge_script = write_merge_pe_script(output_dir, merges, fastq_dir=fastq_dir)
        if merge_script:
            merge_stage = f"merge_pe.sh ({len(merges)} GSM(s))"

    if not fastq_dir:
        ann = apply_uvclap_umi_filenames(annotation)
        return ann, "planned — pass --fastq-dir to write umi_extract.sh", merge_stage

    pairs = collect_uvclap_umi_pairs(fastq_dir, srr_ids)
    if not pairs:
        pairs = planned_uvclap_umi_pairs(fastq_dir, srr_ids)
    script = write_uvclap_umi_extract_script(output_dir, pairs)
    if not script:
        return apply_uvclap_umi_filenames(annotation), "skipped — could not write umi_extract.sh", merge_stage
    return apply_uvclap_umi_filenames(annotation), f"umi_extract.sh ({len(pairs)} library/ies)", merge_stage


def _setup_flash_umi_stage(
    output_dir: Path,
    annotation,
    fastq_dir: Path | None,
    *,
    prefer_cleaned_r1: bool = False,
) -> tuple[Any, str]:
    """Write umi_extract.sh and retarget annotation to SE *_1.umi.fastq.gz uploads.

    UMI extract runs on raw (uncleaned) PE mates so read names stay paired; header
    clean runs on *_1.umi.fastq.gz after extraction when needed.
    """
    srr_ids = list(
        dict.fromkeys(
            srr_from_annotation_file(str(row.get("File", "")))
            for _, row in annotation.iterrows()
            if srr_from_annotation_file(str(row.get("File", "")))
        )
    )
    if not srr_ids:
        return annotation, "skipped — no SRR in annotation"

    if not fastq_dir:
        return apply_umi_extracted_filenames(annotation), "planned — pass --fastq-dir to write umi_extract.sh"

    pairs = collect_flash_umi_pairs(fastq_dir, srr_ids, prefer_cleaned_r1=prefer_cleaned_r1)
    if not pairs:
        pairs = planned_flash_umi_pairs(fastq_dir, srr_ids, prefer_cleaned_r1=prefer_cleaned_r1)
    script = write_umi_extract_script(output_dir, pairs)
    if not script:
        return apply_umi_extracted_filenames(annotation), "skipped — could not write umi_extract.sh"
    return apply_umi_extracted_filenames(annotation), f"umi_extract.sh ({len(pairs)} library/ies)"


def _resolve_fastq_paths_from_annotation(
    fastq_dir: Path | None,
    annotation,
) -> list[tuple[str, Path | None]]:
    """Resolve on-disk FASTQs using annotation File basename, then SRR fallback."""
    from lib.fastq_headers import find_fastq_for_srr

    pairs: list[tuple[str, Path | None]] = []
    for _, row in annotation.iterrows():
        fname = str(row.get("File", "")).strip()
        srr = srr_from_annotation_file(fname)
        if not srr:
            continue
        if fastq_dir and fname:
            candidate = fastq_dir / Path(fname).name
            if candidate.is_file():
                pairs.append((srr, candidate))
                continue
        pairs.append((srr, find_fastq_for_srr(fastq_dir, srr) if fastq_dir else None))
    return pairs


def _run_header_inspection(
    output_dir: Path,
    annotation,
    srr_map: dict,
    barcode_by_gsm: dict[str, BarcodeResolution],
    *,
    fastq_dir: Path | None,
    reads_per_file: int,
    removespace_script: Path | None = None,
    skip_header_clean: bool = False,
) -> tuple[dict[str, str], dict[str, Any], str, str]:
    """Write headers.txt, pipeline_params.json, optional clean_fastq.sh; return params, inspection, statuses."""
    header_stage = ""
    clean_stage = ""
    srr_ids: list[str] = []
    for _, row in annotation.iterrows():
        match = re.search(r"(SRR\d+)", str(row.get("File", "")))
        if match:
            srr_ids.append(match.group(1))
    srr_ids = list(dict.fromkeys(srr_ids))

    srr_paths = _resolve_fastq_paths_from_annotation(fastq_dir, annotation)
    resolved_paths = [path for _srr, path in srr_paths if path and path.exists()]
    inspection = sample_headers_from_fastq_dir(
        [(srr, path) for srr, path in srr_paths if path],
        reads_per_file=reads_per_file,
    )

    if not inspection.fastq_files and fastq_dir:
        return {}, {}, f"no FASTQ found under {fastq_dir}", "skipped — no FASTQ"

    sample_blocks: list[tuple[str, list[str]]] = []
    for srr, path in srr_paths:
        if path and path.exists():
            from lib.fastq_headers import sample_read_headers

            sample_blocks.append((srr, sample_read_headers(path, n_reads=reads_per_file)))

    headers_path = output_dir / "headers.txt"
    if sample_blocks:
        headers_path.write_text(build_headers_txt(sample_blocks), encoding="utf-8")
    elif inspection.sample_headers:
        headers_path.write_text("\n".join(inspection.sample_headers) + "\n", encoding="utf-8")

    five_prime = ""
    for res in barcode_by_gsm.values():
        if res.five_prime:
            five_prime = res.five_prime
            break

    params = derive_clip_pipeline_params(inspection if inspection.sample_headers else None, five_prime_barcode=five_prime)
    inspection_dict = inspection_to_dict(inspection) if inspection.sample_headers else {}

    (output_dir / "pipeline_params.json").write_text(json.dumps(params, indent=2))
    write_analysis_params_hook(
        output_dir,
        params,
        inspection if inspection.sample_headers else None,
        headers_path=headers_path,
    )

    if inspection.sample_headers:
        header_stage = (
            f"headers.txt ({len(inspection.fastq_files)} file(s)); "
            f"move_umi={params['move_umi_to_header']}; "
            f"umi_header_format={params.get('umi_header_format', '')}"
        )
    else:
        header_stage = "skipped — no FASTQ files (prefetch first, then --fastq-dir)"

    if not skip_header_clean and resolved_paths and headers_need_cleaning(inspection.sample_headers):
        rs_script = resolve_removespace_script(removespace_script)
        if rs_script:
            write_clean_fastq_script(output_dir, resolved_paths, removespace_script=rs_script)
            write_upload_manifest(output_dir, resolved_paths)
            clean_stage = f"clean_fastq.sh ({len(resolved_paths)} file(s); slashes/underscores in headers)"
        else:
            clean_stage = "needs removespace — set --removespace-script or install advbfx/flowAPIscripts/preprocessing/removespace.py"
    elif resolved_paths:
        clean_stage = "not needed (headers OK)"
    else:
        clean_stage = "skipped — no FASTQ"

    return params, inspection_dict, header_stage, clean_stage


def _write_flow_delivery_scripts(
    output_dir: Path,
    annotation,
    *,
    flow_project_id: str,
    pipeline_params: dict[str, str],
    fastq_dir: Path | None,
    upload_script: Path | None,
    analysis_script: Path | None,
    upload_dry_run: bool,
) -> tuple[str, str]:
    """Write upload.sh and run_analysis.sh when project id and advbfx scripts are available."""
    upload_stage = "skipped — no flow project id"
    analysis_stage = "skipped — no flow project id"

    if not flow_project_id:
        return upload_stage, analysis_stage

    base_dir = fastq_dir.resolve() if fastq_dir else output_dir
    row_count = len(annotation)
    csv_path = output_dir / "annotation.csv"
    xlsx_path = output_dir / "annotation.xlsx"
    annotation_path = csv_path if csv_path.exists() else xlsx_path
    if not annotation_path.exists():
        upload_stage = "skipped — annotation.csv missing"
        analysis_stage = upload_stage
        return upload_stage, analysis_stage

    up = resolve_advbfx_script("upload/uploadsample_flowbio_v6.py", upload_script)
    an = resolve_advbfx_script("analysis/flowrunanalysis_flowbio.py", analysis_script)

    if up:
        write_upload_script(
            output_dir,
            upload_script=up,
            annotation_path=annotation_path,
            project_id=flow_project_id,
            base_dir=base_dir,
            row_count=row_count,
            dry_run=upload_dry_run,
        )
        upload_stage = f"upload.sh ({row_count} row(s); {annotation_path.name}; dry_run={upload_dry_run})"
    else:
        upload_stage = "skipped — uploadsample_flowbio_v6.py not found"

    params = pipeline_params or {}
    if not params and (output_dir / "pipeline_params.json").exists():
        params = json.loads((output_dir / "pipeline_params.json").read_text())

    if an and params:
        write_analysis_script(
            output_dir,
            analysis_script=an,
            project_id=flow_project_id,
            pipeline_params=params,
            sample_name_filter=sample_name_filter_from_annotation(annotation),
            experimental_method=experimental_method_from_annotation(annotation),
        )
        analysis_stage = f"run_analysis.sh (filter SRR; params from pipeline_params.json)"
    elif not an:
        analysis_stage = "skipped — flowrunanalysis_flowbio.py not found"
    else:
        analysis_stage = "skipped — no pipeline_params.json"

    return upload_stage, analysis_stage


def run_pipeline(
    output_dir: Path,
    matrix_path: Path,
    srr_map_path: Path,
    *,
    scan_pubmed: bool = False,
    pubmed_query: str | None = None,
    pubmed_cache: Path | None = None,
    max_files: int | None = None,
    write_prefetch: bool = False,
    paper_texts: list[tuple[str, Path]] | None = None,
    geo_cache_dir: Path | None = None,
    fetch_geo: bool = False,
    accept_proposals: Path | None = None,
    require_confirmation: bool = True,
    fastq_dir: Path | None = None,
    reads_per_file: int = 5,
    flow_project_id: str = "",
    removespace_script: Path | None = None,
    upload_script: Path | None = None,
    analysis_script: Path | None = None,
    write_flow_scripts: bool = True,
    upload_dry_run: bool = True,
) -> tuple[WorkflowResult | None, bool]:
    output_dir.mkdir(parents=True, exist_ok=True)
    chain = [
        "pubmed-summariser",
        "geo-matrix",
        "barcode-extract",
        "flow-annotate",
        "fastq-headers",
        "header-clean",
        "flash-umi-extract",
        "annotation-xlsx",
        "flow-upload",
        "flow-analysis",
    ]
    stages: dict[str, str] = {}
    flagged: list[dict[str, Any]] = []

    if scan_pubmed:
        _, flagged = run_pubmed_stage(
            output_dir,
            query=pubmed_query or CLIP_ALERT_QUERY,
            use_cache=pubmed_cache,
        )
        stages["pubmed_alert"] = f"{len(flagged)} CLIP paper(s) flagged"
    elif pubmed_cache and pubmed_cache.exists():
        flagged = json.loads(pubmed_cache.read_text(encoding="utf-8"))
        stages["pubmed_alert"] = f"{len(flagged)} CLIP paper(s) from cache"

    matrix_data = parse_geo_matrix(matrix_path)
    gse = matrix_data["series"].get("geo_accession", "")
    pmid = matrix_data["series"].get("pubmed_id", "")
    stages["geo_audit"] = f"{len(matrix_data['samples'])} GSM columns parsed"

    barcode_by_gsm, barcode_stages, paused = _resolve_barcodes_agent_assisted(
        matrix_data,
        paper_texts=paper_texts or [],
        geo_cache_dir=geo_cache_dir,
        fetch_geo=fetch_geo,
        accept_proposals=accept_proposals,
        output_dir=output_dir,
        require_confirmation=require_confirmation,
    )
    stages.update(barcode_stages)

    if paused:
        pause_report = {
            "status": "paused_for_barcode_confirmation",
            "gse": gse,
            "pmid": pmid,
            "stages": stages,
            "next_step": (
                "Edit barcode_proposals.json (set status=confirmed), then re-run with "
                "--accept-proposals barcode_proposals.json"
            ),
        }
        (output_dir / "result.json").write_text(json.dumps(pause_report, indent=2))
        (output_dir / "report.md").write_text(
            "# Flow Compile — paused for barcode confirmation\n\n"
            f"Review `{output_dir / 'CONFIRM_BARCODES.md'}` and confirm proposals.\n"
        )
        return None, True

    resolutions = list(barcode_by_gsm.values())
    resolved = sum(1 for r in resolutions if r.five_prime)

    srr_map = load_srr_map(srr_map_path)
    annotation = build_annotation_table(matrix_data, srr_map, barcode_by_gsm)
    stages["flow_annotate"] = f"{len(annotation)} rows; Organism ∈ {{Hs, Mm, Gg}}"

    flash_study = _annotation_is_flash(annotation, matrix_data)
    uvclap_study = _annotation_is_uvclap(annotation, matrix_data)
    if flash_study:
        annotation = apply_umi_extracted_filenames(annotation)
        stale_clean = output_dir / "clean_fastq.sh"
        if stale_clean.exists():
            stale_clean.unlink()
    elif uvclap_study:
        annotation = apply_uvclap_umi_filenames(annotation)
        stale_clean = output_dir / "clean_fastq.sh"
        if stale_clean.exists():
            stale_clean.unlink()

    umi_on_disk = False
    if fastq_dir and flash_study:
        umi_on_disk = all(
            (fastq_dir / umi_output_basename(srr_from_annotation_file(str(row.get("File", ""))))).is_file()
            for _, row in annotation.iterrows()
            if srr_from_annotation_file(str(row.get("File", "")))
        )

    pipeline_params, header_inspection, header_stage, clean_stage = _run_header_inspection(
        output_dir,
        annotation,
        srr_map,
        barcode_by_gsm,
        fastq_dir=fastq_dir,
        reads_per_file=reads_per_file,
        removespace_script=removespace_script,
        skip_header_clean=flash_study or uvclap_study,
    )
    stages["fastq_headers"] = header_stage
    if flash_study:
        clean_stage = "skipped (FLASH — keep umi_tools headers with spaces for umi_dedup)"
    elif uvclap_study:
        clean_stage = "skipped (uvCLAP — keep umi_tools PE headers for umi_dedup)"
    stages["header_clean"] = clean_stage
    if pipeline_params:
        stages["pipeline_params"] = f"move_umi_to_header={pipeline_params.get('move_umi_to_header')}"

    use_cleaned_names = (output_dir / "clean_fastq.sh").exists() and not flash_study and not uvclap_study
    if use_cleaned_names:
        annotation, _ = _apply_cleaned_filenames(annotation)

    flash_umi_stage = ""
    uvclap_umi_stage = ""
    uvclap_merge_stage = ""
    if flash_study:
        _, flash_umi_stage = _setup_flash_umi_stage(
            output_dir,
            annotation,
            fastq_dir,
            prefer_cleaned_r1=False,
        )
        pipeline_params = derive_flash_post_umi_params()
        stages["flash_umi_extract"] = flash_umi_stage
        (output_dir / "pipeline_params.json").write_text(json.dumps(pipeline_params, indent=2))
        write_analysis_params_hook(
            output_dir,
            pipeline_params,
            None,
            headers_path=output_dir / "headers.txt",
        )
        stages["pipeline_params"] = "move_umi_to_header=false (FLASH post umi_tools extract)"
    elif uvclap_study:
        _, uvclap_umi_stage, uvclap_merge_stage = _setup_uvclap_umi_stage(
            output_dir,
            annotation,
            srr_map,
            fastq_dir,
        )
        pipeline_params = derive_uvclap_post_umi_params()
        stages["uvclap_umi_extract"] = uvclap_umi_stage
        if uvclap_merge_stage:
            stages["uvclap_merge_pe"] = uvclap_merge_stage
        (output_dir / "pipeline_params.json").write_text(json.dumps(pipeline_params, indent=2))
        write_analysis_params_hook(
            output_dir,
            pipeline_params,
            None,
            headers_path=output_dir / "headers.txt",
        )
        stages["pipeline_params"] = (
            "move_umi_to_header=false; trimgalore_params with 3' clip R1=10 R2=5"
        )

    if not flagged and pmid:
        flagged = [
            {
                "pmid": pmid,
                "title": matrix_data["series"].get("title", ""),
                "gse": [gse],
                "status": "from_matrix",
            }
        ]

    result = WorkflowResult(
        gse=gse,
        pmid=pmid,
        gsm_count=len(matrix_data["samples"]),
        file_count=len(annotation),
        barcodes_resolved=resolved,
        barcodes_total=len(resolutions),
        stages=stages,
        barcode_audit=[asdict(r) for r in resolutions],
        chain=chain,
        flow_project_id=flow_project_id,
        pipeline_params=pipeline_params or None,
        header_inspection=header_inspection or None,
    )

    (output_dir / "flagged_papers.json").write_text(json.dumps(flagged, indent=2))
    (output_dir / "barcode_audit.json").write_text(json.dumps(result.barcode_audit, indent=2))
    annotation.to_csv(output_dir / "annotation.csv", index=False)
    try:
        xlsx_path = write_annotation_xlsx(annotation, output_dir / "annotation.xlsx")
        stages["annotation_xlsx"] = xlsx_path.name
    except ImportError:
        stages["annotation_xlsx"] = "skipped — pip install openpyxl"

    if write_flow_scripts and flow_project_id:
        upload_stage, analysis_stage = _write_flow_delivery_scripts(
            output_dir,
            annotation,
            flow_project_id=flow_project_id,
            pipeline_params=pipeline_params or {},
            fastq_dir=fastq_dir,
            upload_script=upload_script,
            analysis_script=analysis_script,
            upload_dry_run=upload_dry_run,
        )
        stages["flow_upload"] = upload_stage
        stages["flow_analysis"] = analysis_stage

    (output_dir / "result.json").write_text(json.dumps(asdict(result), indent=2))
    (output_dir / "report.md").write_text(generate_report(result, flagged))

    if write_prefetch:
        write_prefetch_script(output_dir, annotation["File"].tolist(), max_files)
        if max_files is not None and max_files > 0:
            stages["prefetch"] = f"prefetch.sh (max {max_files} SRR)"
        else:
            stages["prefetch"] = f"prefetch.sh ({len(annotation)} SRR)"
        result.chain.append("prefetch")

    return result, False


def _build_pipeline_kwargs(
    args: argparse.Namespace,
    *,
    output_dir: Path,
    matrix_path: Path,
    srr_map_path: Path,
    scan: bool,
    paper_texts: list,
    geo_cache_dir: Path | None,
    flow_project_id: str,
    pubmed_cache: Path | None = None,
) -> dict[str, Any]:
    return {
        "output_dir": output_dir,
        "matrix_path": matrix_path,
        "srr_map_path": srr_map_path,
        "scan_pubmed": scan,
        "pubmed_query": args.pubmed_query,
        "pubmed_cache": pubmed_cache,
        "max_files": args.max_files if args.max_files > 0 else None,
        "write_prefetch": args.download or args.run_automated,
        "paper_texts": paper_texts,
        "geo_cache_dir": geo_cache_dir,
        "fetch_geo": args.fetch_geo,
        "accept_proposals": args.accept_proposals,
        "require_confirmation": not args.no_require_confirmation,
        "fastq_dir": args.fastq_dir,
        "reads_per_file": args.header_reads,
        "flow_project_id": flow_project_id,
        "removespace_script": args.removespace_script,
        "upload_script": args.upload_script,
        "analysis_script": args.analysis_script,
        "write_flow_scripts": True,
        "upload_dry_run": not args.execute_upload and not args.run_automated,
    }


def run(args: argparse.Namespace) -> int:
    if args.case == "hnrnph":
        matrix_path = HNRNPH_MATRIX
        srr_map_path = HNRNPH_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = []
        geo_cache_dir = SKILL_DIR / "demo"
        flow_project_id = args.flow_project_id or ""
    elif args.case == "gse105082":
        matrix_path = GSE105082_MATRIX
        srr_map_path = GSE105082_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = [(f"paper:{GSE105082_PAPER.name}", GSE105082_PAPER)]
        geo_cache_dir = GSE105082_GEO_CACHE
        flow_project_id = args.flow_project_id or GSE105082_FLOW_PROJECT_ID
    elif args.case == "xl1_dhx9":
        matrix_path = XL1_DHX9_MATRIX
        srr_map_path = XL1_DHX9_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = [(f"paper:{XL1_DHX9_PAPER.name}", XL1_DHX9_PAPER)]
        geo_cache_dir = None
        flow_project_id = args.flow_project_id or XL1_DHX9_FLOW_PROJECT_ID
    elif args.case == "xl9_dhx9":
        matrix_path = XL9_DHX9_MATRIX
        srr_map_path = XL9_DHX9_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = [(f"paper:{XL9_DHX9_PAPER.name}", XL9_DHX9_PAPER)]
        geo_cache_dir = None
        flow_project_id = args.flow_project_id or XL9_DHX9_FLOW_PROJECT_ID
    elif args.case == "xl8_dhx9":
        matrix_path = XL8_DHX9_MATRIX
        srr_map_path = XL8_DHX9_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = [(f"paper:{XL8_DHX9_PAPER.name}", XL8_DHX9_PAPER)]
        geo_cache_dir = None
        flow_project_id = args.flow_project_id or XL8_DHX9_FLOW_PROJECT_ID
    elif args.case == "xl2_hnrnpc":
        matrix_path = XL2_HNRNPC_MATRIX
        srr_map_path = XL2_HNRNPC_SRR_MAP
        pubmed_cache = None
        scan = False
        paper_texts = [(f"paper:{XL2_HNRNPC_PAPER.name}", XL2_HNRNPC_PAPER)]
        geo_cache_dir = None
        flow_project_id = args.flow_project_id or XL2_HNRNPC_FLOW_PROJECT_ID
    elif args.demo:
        matrix_path = DEMO_MATRIX
        srr_map_path = DEMO_SRR_MAP
        pubmed_cache = DEMO_PUBMED_CACHE if not args.scan_pubmed else None
        scan = args.scan_pubmed
        paper_texts = [(f"paper:{p.name}", p) for p in args.paper_text]
        geo_cache_dir = args.geo_cache_dir
        flow_project_id = args.flow_project_id or ""
    else:
        if not args.geo_matrix or not args.srr_map:
            print("Provide --geo-matrix and --srr-map, --demo, or --case.", file=sys.stderr)
            return 2
        matrix_path = Path(args.geo_matrix)
        srr_map_path = Path(args.srr_map)
        pubmed_cache = None
        scan = args.scan_pubmed
        paper_texts = [(f"paper:{p.name}", p) for p in args.paper_text]
        geo_cache_dir = args.geo_cache_dir
        flow_project_id = args.flow_project_id or ""

    if args.paper_text and args.case not in ("hnrnph",):
        paper_texts = [(f"paper:{p.name}", p) for p in args.paper_text]

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    env_path = None
    if args.run_automated or args.execute_upload or args.execute_analysis:
        env_path = ensure_flow_credentials(output_dir, prompt=not args.skip_credential_prompt)
        print(f"✓ Credentials saved → {env_path} (mode 600; do not commit)")

    pipeline_kwargs = _build_pipeline_kwargs(
        args,
        output_dir=output_dir,
        matrix_path=matrix_path,
        srr_map_path=srr_map_path,
        scan=scan,
        paper_texts=paper_texts,
        geo_cache_dir=geo_cache_dir,
        flow_project_id=flow_project_id,
        pubmed_cache=pubmed_cache,
    )

    if args.run_automated:
        if not args.fastq_dir:
            print("--fastq-dir is required with --run-automated", file=sys.stderr)
            return 2
        if not args.accept_proposals:
            print("--accept-proposals is required (confirm barcodes before automated run)", file=sys.stderr)
            return 2

        compile_argv = [a for a in sys.argv if a != "--run-automated"]
        if env_path:
            write_run_workflow_script(
                output_dir,
                env_path=env_path,
                fastq_dir=args.fastq_dir,
                poll_interval=args.poll_interval,
                compile_argv=compile_argv,
            )
            print(f"✓ Visible terminal script → {output_dir / 'run_workflow.sh'}")
            print(f"  Live log: tail -f {output_dir / 'logs' / 'workflow.log'}")

        def compile_fn(**overrides: Any):
            return run_pipeline(**{**pipeline_kwargs, **overrides})

        return run_automated_workflow(
            output_dir,
            args.fastq_dir,
            compile_fn=compile_fn,
            compile_kwargs=pipeline_kwargs,
            poll_interval=args.poll_interval,
            prompt_credentials=False,
        )

    result, paused = run_pipeline(**pipeline_kwargs)

    if paused:
        print("⏸ Paused — barcode proposals need human confirmation")
        print(f"  Review: {output_dir / 'CONFIRM_BARCODES.md'}")
        print(f"  Edit:   {output_dir / 'barcode_proposals.json'}")
        print("  Then:   --accept-proposals barcode_proposals.json")
        return EXIT_PAUSED

    assert result is not None
    print(f"✓ Chain: {' → '.join(result.chain)}")
    print(f"✓ GSE {result.gse}: {result.barcodes_resolved}/{result.barcodes_total} barcodes resolved")
    print(f"✓ {result.file_count} annotation rows → {output_dir / 'annotation.csv'}")
    if (output_dir / "annotation.xlsx").exists():
        print(f"✓ Upload sheet → {output_dir / 'annotation.xlsx'}")
    print(f"✓ Report → {output_dir / 'report.md'}")
    if (output_dir / "headers.txt").exists():
        print(f"✓ Headers → {output_dir / 'headers.txt'}")
    if (output_dir / "pipeline_params.json").exists():
        params = json.loads((output_dir / "pipeline_params.json").read_text())
        print(
            f"✓ Pipeline params → move_umi_to_header={params.get('move_umi_to_header')}, "
            f"umi_separator={params.get('umi_separator')}, "
            f"umi_header_format={params.get('umi_header_format', '')}"
        )
    if (output_dir / "clean_fastq.sh").exists():
        print(f"✓ Header clean → {output_dir / 'clean_fastq.sh'} (run before upload)")
    if (output_dir / "upload.sh").exists():
        mode = "dry-run" if not args.execute_upload else "live"
        print(f"✓ Upload script ({mode}) → {output_dir / 'upload.sh'}")
    if (output_dir / "run_analysis.sh").exists():
        print(f"✓ Analysis script → {output_dir / 'run_analysis.sh'}")
    if result.flow_project_id:
        print(f"✓ Flow project → https://app.flow.bio/projects/{result.flow_project_id}/")
    if args.download:
        print(f"✓ Prefetch → {output_dir / 'prefetch.sh'}")

    if args.execute_upload:
        script = output_dir / "upload_live.sh"
        if not script.exists():
            script = output_dir / "upload.sh"
        if script.exists():
            rc = run_shell_step(
                "Flow upload",
                script,
                output_dir / "logs" / "upload.log",
                poll_interval=args.poll_interval,
            )
            if rc != 0:
                return rc

    if args.execute_analysis and (output_dir / "run_analysis.sh").exists():
        rc = run_shell_step(
            "Flow CLIP analysis",
            output_dir / "run_analysis.sh",
            output_dir / "logs" / "analysis.log",
            poll_interval=args.poll_interval,
        )
        if rc != 0:
            return rc

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Flow Compile — CLIP orchestrator")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--demo", action="store_true", help="GSE118265 FLASH demo")
    parser.add_argument(
        "--case",
        choices=["hnrnph", "gse105082", "xl1_dhx9", "xl2_hnrnpc", "xl8_dhx9", "xl9_dhx9"],
        help="Preset: hnrnph (GSE303135), gse105082 (DHX9 iCLIP), xl1_dhx9 (GSE89276), xl2_hnrnpc (GSE94781), xl8_dhx9 (GSE89751), xl9_dhx9 (GSE89598) FLASH",
    )
    parser.add_argument("--geo-matrix", type=Path)
    parser.add_argument("--srr-map", type=Path)
    parser.add_argument(
        "--paper-text",
        type=Path,
        action="append",
        default=[],
        help="Methods text file, e.g. PMC6307142 excerpt (repeatable; optional corpus)",
    )
    parser.add_argument("--geo-cache-dir", type=Path, help="Cached GEO sample text files geo_GSM*.txt")
    parser.add_argument("--fetch-geo", action="store_true", help="Live-fetch GEO sample pages")
    parser.add_argument("--accept-proposals", type=Path, help="Confirmed barcode_proposals.json")
    parser.add_argument(
        "--no-require-confirmation",
        action="store_true",
        help="Auto-accept extracted barcode proposals (not recommended)",
    )
    parser.add_argument("--scan-pubmed", action="store_true")
    parser.add_argument("--pubmed-query")
    parser.add_argument("--download", action="store_true")
    parser.add_argument(
        "--max-files",
        type=int,
        default=0,
        help="Cap prefetch SRR count (0 = all samples in series; default)",
    )
    parser.add_argument(
        "--fastq-dir",
        type=Path,
        help="Directory with prefetched FASTQ files for headers.txt + pipeline param inference",
    )
    parser.add_argument(
        "--header-reads",
        type=int,
        default=5,
        help="FASTQ records to sample per file into headers.txt (default 5)",
    )
    parser.add_argument(
        "--flow-project-id",
        help="Flow.bio project ID (gse105082 preset defaults to 997999200849251656)",
    )
    parser.add_argument(
        "--removespace-script",
        type=Path,
        help="Path to flowAPIscripts/preprocessing/removespace.py (auto-detected in advbfx)",
    )
    parser.add_argument(
        "--upload-script",
        type=Path,
        help="Path to uploadsample_flowbio_v6.py (auto-detected in advbfx)",
    )
    parser.add_argument(
        "--analysis-script",
        type=Path,
        help="Path to flowrunanalysis_flowbio.py (auto-detected in advbfx)",
    )
    parser.add_argument(
        "--upload",
        action="store_true",
        help="Alias for generating upload.sh (always generated when project id set)",
    )
    parser.add_argument(
        "--execute-upload",
        action="store_true",
        help="Run upload.sh after compile (default upload.sh uses --dry-run unless this flag is set)",
    )
    parser.add_argument(
        "--execute-analysis",
        action="store_true",
        help="Run run_analysis.sh with 4-minute status polling",
    )
    parser.add_argument(
        "--run-automated",
        action="store_true",
        help="Full workflow: credentials → download → clean → upload → analysis (4-min polling)",
    )
    parser.add_argument(
        "--poll-interval",
        type=int,
        default=DEFAULT_POLL_INTERVAL_SEC,
        help="Seconds between status checks for download/upload/analysis (default: 240)",
    )
    parser.add_argument(
        "--skip-credential-prompt",
        action="store_true",
        help="Require FLOWBIO_USERNAME/PASSWORD in environment; do not prompt",
    )
    return run(parser.parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
